package com.lovorise.app.libs.shared_prefs

object PreferencesKeys {

    const val IS_RATING_DIALOG_PRESENTED = "IS_RATING_DIALOG_PRESENTED"
    const val AUTH_TOKEN = "AUTH_TOKEN"
    const val REFRESH_TOKEN = "REFRESH_TOKEN"
    const val CURRENT_SIGNUP_PAGE = "CURRENT_SIGNUP_PAGE"
    const val SIGN_UP_COMPLETED = "SIGN_UP_COMPLETED"
    const val CURRENT_EMAIL = "CURRENT_EMAIL"
    const val IS_LOGGED_IN = "IS_LOGGED_IN"
    const val IS_REELS_MOVE_UP_SHOWN = "IS_REELS_MOVE_UP_SHOWN"
    const val IS_NOT_INTERESTED_DIALOG_SHOWN = "IS_NOT_INTERESTED_DIALOG_SHOWN"
    const val IS_INTERESTED_DIALOG_SHOWN = "IS_INTERESTED_DIALOG_SHOWN"
    const val IS_SKIP_TEMPORARY_DIALOG_SHOWN = "IS_SKIP_TEMPORARY_DIALOG_SHOWN"
    const val IS_HEART_SHOP_WELCOME_DIALOG_SHOWN = "IS_HEART_SHOP_WELCOME_DIALOG_SHOWN"
    const val IS_SWIPE_GUIDELINES_SHOWN = "IS_SWIPE_GUIDELINES_SHOWN"
    const val APP_LANGUAGE = "APP_LANGUAGE"
    const val LAST_LOGIN_TYPE = "LAST_LOGIN_TYPE"
    const val CURRENT_THEME = "CURRENT_THEME"
    const val REFERRAL_CODE = "REFERRAL_CODE"
}